# org: greatcodeeer
app: vevue
service: web

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  lambdaHashingVersion: 20201221

functions:
  nuxt:
    handler: handler.nuxt
    events:
      - http:
          path: '/'
          method: get
      - http:
          path: '{proxy+}'
          method: get

plugins:
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - '*/*'
